name: initsurvey
description: A new Flutter application.
version: 1.0.0+1

environment:
  sdk: '>=3.11.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  provider: ^6.1.2
  connectivity: ^3.0.6
  shared_preferences: ^2.2.2
  http: ^1.2.1
  webview_flutter: ^4.7.0
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/ui/
    - assets/images/locale/
    - assets/images/pattern/
    - assets/datas/
    - assets/administrations/
    - assets/administrations/quan-huyen/
    - assets/administrations/xa-phuong/
    - assets/locale/en/
    - assets/locale/vi/
